class Default:
    settings = {
        "Graph_Visual_Settings": "",
        "x_axis_title": "x_axis title",
        "y_axis_title": "y_axis title",
        "title": "Graph Title",
        "xmin": -5.0,
        "xmax": 5.0,
        "ymin": -5.0,
        "ymax": 5.0,
        "arrow_scale": 0.5,
        "starting_points": [[1,1],],
        "show_legend": True,
        "Graph_Background_Settings": "",
        "h": 0.01,
        "xdensity": 20,
        "ydensity": 20,
        "specify_time": False,
        "forward_steps": 1000,
        "backward_steps": 1000,
        "forward_time": 10,
        "backward_time": 10,
        "method": "Euler",
        "Warning_Settings": "",
        "stop_all_warnings": False,
        "stop_variable_override_warning": False,
        "stop_termination_warning": False,
        "stop_numerical_termination_warning": False,
        "stop_improper_power_plotted_lines_warning": False,
        "stop_improper_power_phase_plot_warning": False,
        "stop_invalid_value_in_function_in_phase_plot_warning": False,
        "stop_invalid_value_in_function_in_plotted_lines_warning": False,
        "stop_overflow_in_phase_plot_warning": False,
        "stop_overflow_in_plotted_lines_warning": False,
        "stop_underflow_in_phase_plot_warning": False,
        "stop_underflow_in_plotted_lines_warning": False,
        "Files_Settings": "",
        "settings_file": "\settings.json",
        "cwd": "current_working_directory_stored_here"
    }